import { z } from 'zod'

export const quoteSchema = z.object({
  HST: z.number(),
  baseRate: z.number(),
  calculatedDistance: z.number(),
  createdAt: z.string(),
  destination_formatted_address: z.string(),
  destination_name: z.string(),
  destination_place_id: z.string(),
  distanceText: z.string(),
  distanceValue: z.number(),
  durationText: z.string(),
  durationValue: z.number(),
  endLat: z.number(),
  endLng: z.number(),
  firstName: z.string(),
  fuelSurcharge: z.number(),
  gratuity: z.number(),
  hoursLabel: z.string(),
  hoursValue: z.number(),
  id: z.string(),
  isItHourly: z.boolean(),
  isRoundTrip: z.boolean(),
  lastName: z.string(),
  origin_formatted_address: z.string(),
  origin_name: z.string(),
  origin_place_id: z.string(),
  passengersLabel: z.string(),
  passengersValue: z.number(),
  pickupDate: z.string(),
  pickupTime: z.string(),
  returnDate: z.string(),
  returnTime: z.string(),
  serviceTypeLabel: z.string(),
  serviceTypeValue: z.number(),
  startLat: z.number(),
  startLng: z.number(),
  totalFare: z.number(),
  updatedAt: z.string(),
  userEmail: z.string(),
  userId: z.null(),
  vehicleTypeLabel: z.string(),
  vehicleTypeValue: z.number(),
  quote_number: z.number(),
  isPearsonAirportPickup: z.boolean(),
  isPearsonAirportDropoff: z.boolean(),
  addedToCart: z.boolean(),
  isBooked: z.boolean(),
  utm_medium: z.string(),
  utm_source: z.string(),
  utm_campaign: z.string(),
  utm_term: z.string(),
  gclid: z.string(),
  vehicle_type: z.object({
    vehicle_image: z.string(),
  }),
})

export type Quote = z.infer<typeof quoteSchema>
